# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Lingua-LinkParser-MatchPath
version:      0.02
version_from: lib/Lingua/LinkParser/MatchPath.pm
installdirs:  site
requires:
    Exporter::Lite:                0.01
    Lex:                           0
    Lingua::LinkParser:            1
    Parse::Yapp:                   0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
